apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
 name: linguasphere-dev
 namespace: argocd
spec:
 project: default
 source:
   repoURL: https://github.com/khanhlinh-create/linguasphere-k8s.git
   targetRevision: main
   path: charts/linguasphere
   helm:
     valueFiles:
       - values-dev.yaml
 destination:
   server: https://kubernetes.default.svc
   namespace: linguasphere-dev
 syncPolicy:
   automated:
     prune: true
     selfHeal: true
   syncOptions:
     - CreateNamespace=true
