apiVersion: apps/v1
kind: Deployment
metadata:
 name: backend
 namespace: {{ .Values.namespace }}
 labels:
   app: backend
spec:
 replicas: {{ .Values.backend.replicas }}
 selector:
   matchLabels:
     app: backend
 template:
   metadata:
     labels:
       app: backend
   spec:
     containers:
       - name: backend
         image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
         imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
         ports:
           - containerPort: {{ .Values.backend.port }}
         env:
           - name: PORT
             value: "{{ .Values.backend.port }}"
           - name: MONGODB_URI
             valueFrom:
               secretKeyRef:
                 name: backend-secrets
                 key: mongodb_uri
           - name: DB_NAME
             valueFrom:
               secretKeyRef:
                 name: backend-secrets
                 key: db_name
           - name: JWT_SECRET
             valueFrom:
               secretKeyRef:
                 name: backend-secrets
                 key: jwt_secret
