apiVersion: v1
kind: Service
metadata:
  name: linguasphere-backend
  labels:
    app: linguasphere-backend
spec:
  type: ClusterIP
  selector:
    app: linguasphere-backend
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      protocol: TCP